services:
  binaries:
    image: golang:1.23.5-alpine
    container_name: binaries 
    volumes:
      - go_binaries:/go/bin
    command: >
      sh -c "
        go install github.com/bokwoon95/wgo@latest
      "

  auth:
    image: golang:1.23.5-alpine
    working_dir: /usr/local/src/auth
    container_name: auth 
    volumes:
      - ./:/usr/local/src/auth
      - go_binaries:/go/bin
    command: sh -c "wgo run main.go"
    ports:
      - "3000:3000"
    depends_on:
      binaries:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres 
    environment:
      POSTGRES_USER: auth 
      POSTGRES_PASSWORD: serious-password 
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "auth"]
      interval: 5s
      retries: 5

volumes:
  go_binaries:
  postgres_data:
